import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";
import AnimatedLayout from "@/components/providers/AnimatedLayout";
import { ConfirmProvider } from "@/components/confirm/ConfirmProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-playfair",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
      className={`${playfair.variable} ${inter.variable} 
      antialiased bg-background text-foreground transition-colors duration-300`
      }>
        <div className="min-h-screen bg-backgorund text-foreground">
        <Toaster position="top-right" />
        <AuthProvider>
          <ConfirmProvider>
            <AnimatedLayout>{children}</AnimatedLayout>
          </ConfirmProvider>
        </AuthProvider>

        </div>
      </body>
    </html>
  );
}
